### ISSUE TITLE
Last line in level is not parsed

### ISSUE THREAD

**Issue by DrDimon** [Pilen/aimas#1]
Den sidste linje af et level bliver ikke parsed fordi (eller hvis) der ikke er et linjeskift. Jeg vidste ikke om jeg bare kunne slette linjskift checket, så det får du lov til.

**Comment by Pilen** [comment]
Checket er indført fordi go er tåbeligt med hensyn til CRLF filer
af en eller anden grund bliver CRLF konverteret til LFLF, altså to almindelige linjeskift, hvilket gør  at hver anden linje er blank.
Jeg ved ikke om det kan ændres ved at sætte et andet locale, men problemet er at de udleverede filer er lidt tilfældige i forhold til hvilket format de bruger.

Så lige nu droppes alle blanke linjer, så må vi bare håbe på at der ikke er nogen legitime baner der har blanke linjer.
